"""
HTML template for generated blog articles
"""

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{meta_description}">
    <meta name="keywords" content="{topic}, {category_name}">
    <meta name="author" content="AI Site Generator">
    <meta name="generator" content="AI Site Generator">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{meta_description}">
    <meta property="og:type" content="article">
    <title>{title}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Georgia', 'Times New Roman', serif;
            line-height: 1.8;
            color: #333;
            background-color: #fafafa;
        }}
        
        .container {{
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        
        header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 60px 20px;
            text-align: center;
            margin-bottom: 40px;
        }}
        
        header h1 {{
            font-size: 2.5rem;
            margin-bottom: 15px;
            font-weight: 700;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
        }}
        
        .category-badge {{
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 8px 20px;
            border-radius: 25px;
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        
        .meta {{
            color: #666;
            font-size: 0.9rem;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }}
        
        article {{
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 2px 15px rgba(0,0,0,0.08);
            margin-bottom: 40px;
        }}
        
        article h1 {{
            font-size: 2rem;
            color: #2d3748;
            margin-bottom: 20px;
            line-height: 1.3;
        }}
        
        article h2 {{
            font-size: 1.5rem;
            color: #4a5568;
            margin-top: 35px;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #667eea;
        }}
        
        article h3 {{
            font-size: 1.25rem;
            color: #4a5568;
            margin-top: 25px;
            margin-bottom: 12px;
        }}
        
        article p {{
            margin-bottom: 18px;
            text-align: justify;
        }}
        
        article ul, article ol {{
            margin: 20px 0;
            padding-left: 30px;
        }}
        
        article li {{
            margin-bottom: 10px;
        }}
        
        article strong {{
            color: #2d3748;
        }}
        
        article em {{
            color: #667eea;
        }}
        
        article blockquote {{
            border-left: 4px solid #667eea;
            padding: 15px 20px;
            margin: 25px 0;
            background: #f7fafc;
            font-style: italic;
            color: #4a5568;
        }}
        
        article a {{
            color: #667eea;
            text-decoration: none;
            border-bottom: 1px solid transparent;
            transition: border-color 0.2s;
        }}
        
        article a:hover {{
            border-bottom-color: #667eea;
        }}
        
        footer {{
            text-align: center;
            padding: 30px;
            color: #718096;
            font-size: 0.85rem;
        }}
        
        @media (max-width: 768px) {{
            header h1 {{
                font-size: 1.8rem;
            }}
            
            article {{
                padding: 25px;
            }}
        }}
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>{topic}</h1>
            <span class="category-badge">{category_name}</span>
        </div>
    </header>
    
    <main class="container">
        <div class="meta">
            <span>Published on {published_date}</span> &bull;
            <span>Category: {category_name}</span>
        </div>
        
        <article>
            {content}
        </article>
    </main>
    
    <footer>
        <p>Generated by AI Site Generator on {generated_date}</p>
        <p>Topic: {topic} | Category: {category_name}</p>
    </footer>
</body>
</html>"""


def render_html_page(
    topic: str,
    category: str,
    category_name: str,
    content: str,
    meta_description: str = None,
    published_date: str = None,
    generated_date: str = None
) -> str:
    """Render an HTML page from the template."""
    from datetime import datetime
    
    now = datetime.utcnow()
    
    if not meta_description:
        meta_description = f"Learn about {topic} with a focus on {category_name.lower()}. Comprehensive article covering key insights and information."
    
    if not published_date:
        published_date = now.strftime("%B %d, %Y")
    
    if not generated_date:
        generated_date = now.strftime("%Y-%m-%d %H:%M")
    
    title = f"{topic}: {category_name}"
    
    return PAGE_TEMPLATE.format(
        title=title,
        topic=topic,
        category=category,
        category_name=category_name,
        content=content,
        meta_description=meta_description,
        published_date=published_date,
        generated_date=generated_date,
    )
